### ISSUE TITLE
Using SoapyAirspy with RX_TOOLS... how can i activate BIAS-T?

### ISSUE THREAD

**Issue by runahue** [pothosware/SoapyAirspy#15]
Hello friends:
Is anybody using rx_tools (https://github.com/rxseger/rx_tools) with Airspy?
Is possible activate bias-t?
rx_tools uses SoapyAirspy.
A lot of thank's 4 your help.

**Comment by guruofquality** [comment]
I added support to apply any device arguments to the arbitrary settings when the keys match: https://github.com/pothosware/SoapyAirspy/commit/4a4892eaadea44e3060983088c73d6d8d975eec8

So you can shove "biastee=true" (for example) into the device arguments string which may command line sdr applications support. I didnt test it, so let us know, thanks!

**Comment by runahue** [comment]
A lot of thank's !
I will test it next days.
Now i am fighting with rx_tools.... I think they have some bugs.

**Comment by doctorvenables** [comment]
bump

I've tried combinations of biastee=true. Stabbing in the dark a bit,
Is it
-d biastee=true
-d biastee=1
-d biastee:1
-d "biastee=true"

or am I missing the right combination completely.

The short term answer is to remove the LNA/filter up by the antenna, try without the biastee setting on the airspy and see if I can get something. Not ideal long term but at least I'd have isolated the problem.

Extra info: I'm on raspbian buster on a Pi4, airspy_rx is completely fine (and I can switch on the biastee with the -b 1 option so I know it works)

**Comment by guruofquality** [comment]
* The -t option in rx_sdr will write arbitrary key value settings: https://github.com/rxseger/rx_tools/blob/master/src/rtl_sdr.c#L193 The format with the biastee=true would be correct one.

Note that this is only in one of the rx tools applications, if you need it on others please make a pull request to have a command line option with a call to verbose_settings(). It should be a pretty minimal change. I can merge pulls on that repo FWIW

**Comment by guruofquality** [comment]
This should be an issue with rx tools, closing. thanks!

**Comment by doctorvenables** [comment]
Thanks for the advice. 
Appreciate the hard work that's gone into soapyairspy.
Have made a pull request (don't know if I've done it right though!)
