### ISSUE TITLE
getNativeStreamFormat() gives wrong fullScale value

### ISSUE THREAD

**Issue by szpajder** [pothosware/SoapyAirspy#16]
`SoapyAirspy::getNativeStreamFormat` returns 65536 as `fullScale`. But the native format is signed short, so it shall in fact be 32767, right?

65536 (or rather 65535) would be more appropriate for unsigned short.

**Comment by guruofquality** [comment]
Yea, thats probably the case, it should be for the signed int16 scaling. Fixed on master.
Thanks!
