### ISSUE TITLE
Airspy HF+ support

### ISSUE THREAD

**Issue by streamofstars** [pothosware/SoapyAirspy#17]
I am lucky to have both Airspy Mini and Airspy HF+ I have just installed all required packages, all utility packages except the ones for Python3 and relevant hardware packages (airspy) from [PothosCore github](https://github.com/pothosware/PothosCore/wiki/Ubuntu) for Ubuntu.

Executing
`SoapySDRUtil --probe`
when Airspy Mini is connected returns various info about the hardware and I can connect to it remotely and it works. When the same is tried with Airspy HF+ the below happens:

```
SoapySDRUtil --probe 
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Probe device 
Error probing device: device_id missing.
```

The device itself seems to be undamaged tried with GQRX on another computer and it works. Is it just unsupported yet or is this unexpected behavior?

Other info that might be useful:

```
dmesg | tail
[ 1181.654312] usb 3-2: new high-speed USB device number 3 using xhci_hcd
[ 1181.787154] usb 3-2: New USB device found, idVendor=03eb, idProduct=800c
[ 1181.787171] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1181.787180] usb 3-2: Product: AIRSPY HF+
[ 1181.787188] usb 3-2: Manufacturer: www.airspy.com
[ 1181.787195] usb 3-2: SerialNumber: AIRSPYHF SN:<serial-no-redacted>

lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 03eb:800c Atmel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

SoapySDRUtil --info
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

Lib Version: v0.6.1-myriadrf~xenial
API Version: v0.6.0
ABI Version: v0.6
Install root: /usr
Search path: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.6
Search path: /usr/local/lib/x86_64-linux-gnu/SoapySDR/modules0.6
Search path: /usr/local/lib/SoapySDR/modules0.6
Module found: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.6/libairspySupport.so
Module found: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.6/libosmosdrSupport.so
Module found: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.6/libremoteSupport.so
Loading modules... done
Available factories...airspy, null, osmosdr, remote, 

PothosUtil --system-info
Lib Version: 0.6.0-ppa1~xenial
API Version: 0.6.0
ABI Version: 0.6
Root Path: /usr
Data Path: /usr/share/Pothos
User Data: /home/<user>/.local/share/Pothos
User Config: /home/<user>/.config/Pothos
Runtime Library: /usr/lib/x86_64-linux-gnu/libPothos.so.0.6.0
Util Executable: /usr/bin/PothosUtil
Dev Include Path: /usr/include
Dev Library Path: /usr/lib/x86_64-linux-gnu

sh -c "uname -a;lsb_release -a"
Linux <hostname> 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
CPU is: AMD G-T56N (2) @ 1.650GHz

**Comment by guruofquality** [comment]
For AirspyHF support, it looks like you should be using: this repo: https://github.com/stottsc/SoapyAirspyHF and see this issue for more info: https://github.com/pothosware/SoapySDR/issues/141 Its pretty new, so the author may need whatever bug reports you have on the SoapyAirspyHF project.

In regards to the error `Error probing device: device_id missing.` If you didnt have SoapyAirspyHF installed, and this came from the SoapyAirspy project, then we probably need to figure out how to not have it be affected by airspyhf, if theres going to be two different projects for this hardware series. So is that the case, so there might be something to fix anyway?

Anyway, let me know if I assumed wrong. I dont have airspy's, but I'm just trying to keep these projects coherent. :-)
