### ISSUE TITLE
ppm settings for Airspy driver appears to be ignored ?

### ISSUE THREAD

**Issue by zanco** [pothosware/SoapyAirspy#27]
Hi, 
I am running openwebrx with Airspy mini.

At 403 MHz the Airspy is about 1.5 kHz off. I tried to set the ppm value in the openwebrx config, but that does not affect anything. I tried even values -2000 to + 2000 but no change at all.

The developer of the openwebrx.de version of the software writes the problem would be in the API ?

> I have checked the source code of the SoapyAirspy module, and it seems like it doesn't implement the necessary API, which basically makes the setting useless and also makes it impossible for OpenWebRX to correct the frequency offset. This is the second SoapySDR module that is lacking in that regard, the other seems to be the HackRF (see here). You are of course free to try and let me know if it does work, I'd be surprised if it does though.

> Since this is beyond the scope of OpenWebRX, I can only advise you contact the developers of the SoapyAirspy module to implement the setFrequencyCorrection() API.

So here I am, can this be fixed pleae ?

Thanks,

Ben

**Comment by guruofquality** [comment]
There is not a lot in this API, which call adjusts frequency correction in PPM? https://github.com/airspy/airspyone_host/blob/master/libairspy/src/airspy.h

for example rtlsdr has `rtlsdr_set_freq_correction` https://github.com/steve-m/librtlsdr/blob/master/include/rtl-sdr.h#L162

**Comment by jketterl** [comment]
Full discussion here: https://groups.io/g/openwebrx/topic/79360293

Other members have already pointed out that the PPM value on the device can only be set through a special "Windows tool" (I can't be more specific since I can only quote that part). So, unless Airspy release a new product library to support this functionality, this cannot be fixed here.

Sorry for any confusion this may have caused.

**Comment by guruofquality** [comment]
Cool, well if they ever come up with a way to do it, a PR is always welcome! thanks
