### ISSUE TITLE
Sample type handling

### ISSUE THREAD

**Issue by touil** [pothosware/SoapyAirspy#6]
https://github.com/pothosware/SoapyAirspy/blob/master/Streaming.cpp#L147

I was expecting airspy_set_sample_type(dev, asFormat);

**Comment by cjcliffe** [comment]
@touil thanks; I had left it hard-coded since It's only doing a cast conversion from FLOAT to INT16 at the moment instead of using the proper libairspy sample type facilities -- will fix this up once the support is implemented.

**Comment by guruofquality** [comment]
I dont have an airspy to test, but I implemented this feature on the [streaming work branch](https://github.com/pothosware/SoapyAirspy/tree/streaming_work). Any volunteers to give a quick int16 test or confirm floats still work?
